<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Scada.Core\Scada.Core.csproj" />
    <ProjectReference Include="..\..\src\Scada.Scene\Scada.Scene.csproj" />
    <ProjectReference Include="..\..\src\Scada.Storage\Scada.Storage.csproj" />
    <ProjectReference Include="..\..\src\Scada.Simulator\Scada.Simulator.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
</Project>
