<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Scada.Storage</AssemblyName>
    <RootNamespace>Scada.Storage</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Scada.Core\Scada.Core.csproj" />
    <ProjectReference Include="..\Scada.Scene\Scada.Scene.csproj" />
    <PackageReference Include="JsonSchema.Net" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="..\..\schemas\project-v1.schema.json" Link="Schemas\project-v1.schema.json" />
  </ItemGroup>
</Project>
