<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Scada.Controls.Svg</AssemblyName>
    <RootNamespace>Scada.Controls.Svg</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Scada.Controls\Scada.Controls.csproj" />
  </ItemGroup>
</Project>
