<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Scada.Gateway</AssemblyName>
    <RootNamespace>Scada.Gateway</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Scada.Runtime\Scada.Runtime.csproj" />
    <ProjectReference Include="..\Scada.Core\Scada.Core.csproj" />
    <ProjectReference Include="..\Scada.Storage\Scada.Storage.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
  </ItemGroup>
</Project>
