<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <AssemblyName>Scada.Simulator</AssemblyName>
    <RootNamespace>Scada.Simulator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Scada.Core\Scada.Core.csproj" />
  </ItemGroup>
</Project>
