<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Scada.Controls.Wpf\Scada.Controls.Wpf.csproj" />
    <ProjectReference Include="..\..\src\Scada.Controls.Svg\Scada.Controls.Svg.csproj" />
    <ProjectReference Include="..\..\samples\Scada.Controls.SampleProject\Scada.Controls.SampleProject.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>
</Project>
